### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by ghost** [adamnpeace/micro-wc-plugin#1]
Dear adamnpeace,

Please see: (repo deleted since it was merged)

I forked your code, added a few features. If you're okay with the changes, please consider updating your repository.
If you don't at least please tell me if you're okay with me forking your code under the MIT license, and renaming to a different name (wc-plus or something), and applying to the main plugin repo.

Thanks,

Sincerely,

- productive

**Comment by adamnpeace** [comment]
Hi,

Absolutely, seems like you made some good improvements. 

In future I advise you to either:
- fork the repository in GitHub or,
- clone the repo then add a new remote to your workspace

Doing this will also allow you to create a Pull Request in GH rather than needing to opening an issue.

In this case, I merged your repo from gitgud.io into the `line-count` branch.

Please make your own Pull Request for `line-count -> master` so you appear on the list of collaborators. Otherwise, I will create the PR myself but you will not appear on the authors list.

Thanks.

**Comment by adamnpeace** [comment]
Hi @Productive2,

I will make the pull request myself in 48 hours.

**Comment by ghost** [comment]
I'm sorry for the late reply! It's fine like this (I don't really mind not becoming a collaborator), next time I'll make sure to try cloning.
I'm closing the issue now.

Thanks,

Sincerely,

Productive
